apiVersion: v1
kind: Service
metadata:
  name: gamestore
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: gamestore
  type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gamestore-env
data:
  GAMESTORE_ENV_DATA
  
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gamestore
spec:
  backend:
    serviceName: gamestore
    servicePort: 80

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gamestore
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gamestore
    spec:
      containers:
      - name: gamestore
        image: GAMESTORE_IMAGE
        envFrom:
          - configMapRef:
              name: gamestore-env
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5